services:
  - type: web
    name: formulaepi-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_TO_EMAIL
        sync: false

